services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: blog
      POSTGRES_ROOT_PASSWORD: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - v-data:/var/lib/mysql

volumes:
  v-data: